# Generated by Django 4.1.3 on 2022-12-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigosConsulta',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'codigos_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comparendos',
            fields=[
                ('id_comparendo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fotodeteccion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Comparendo'), ('2', 'Resolución'), ('3', 'Cobro'), ('4', 'Archivado')], max_length=11, null=True)),
                ('fecha_imposicion', models.DateField(blank=True, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('fecha_cobro_coactivo', models.DateField(blank=True, null=True)),
                ('numero_resolucion', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_cobro_coactivo', models.CharField(blank=True, max_length=30, null=True)),
                ('placa', models.CharField(blank=True, max_length=6, null=True)),
                ('servicio_vehiculo', models.CharField(blank=True, choices=[('1', 'Particular'), ('2', 'Oficial'), ('3', 'Otros'), ('4', 'Publico'), ('5', 'No reportado'), ('6', 'Diplomatico')], max_length=12, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('1', 'AUTOMOVIL'), ('2', 'MOTOCICLETA'), ('3', 'CAMION'), ('4', 'CAMIONETA'), ('5', 'BUSETA'), ('6', 'MICROBUS'), ('7', 'DESCONOCIDA'), ('8', 'CAMPERO'), ('9', 'TRACTO/CAMION')], max_length=13, null=True)),
                ('secretaria', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('valor_neto', models.FloatField(blank=True, null=True)),
                ('valor_pago', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comparendos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('id_infraccion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('inmovilizacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infracciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrizaciones',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('valor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parametrizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('RC', 'RC'), ('NIP', 'NIP'), ('NUIP', 'NUIP'), ('NIT', 'NIT'), ('PA', 'PA')], max_length=4, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('Persona natural', 'Persona natural'), ('Persona jurídica', 'Persona jurídica')], max_length=16, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('movil', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_consulta_comp', models.DateTimeField(blank=True, null=True)),
                ('consulta_recurrente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalariosMensuales',
            fields=[
                ('id_salarios_mensuales', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('anio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salarios_mensuales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('infraccion', models.CharField(blank=True, max_length=5, null=True)),
                ('smldv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sanciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token_key', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id_log', models.OneToOneField(db_column='id_log', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core_system.codigosconsulta')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('CRM', 'CRM'), ('Juzto.co', 'Juzto.co'), ('Webhook externo', 'Webhook externo')], max_length=15)),
                ('destino', models.CharField(choices=[('Verifik', 'Verifik'), ('Bot SIMIT', 'Bot SIMIT'), ('Bot Bogotá', 'Bot Bogotá'), ('Bot Medellín', 'Bot Medellín')], max_length=12)),
                ('resultado', models.IntegerField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
    ]
