# Generated by Django 4.1.4 on 2022-12-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('fecha_consulta', models.DateTimeField()),
            ],
            options={
                'db_table': 'log_multas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id_comparendo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_comparendo', models.CharField(blank=True, max_length=45, null=True)),
                ('comparendo_electronico', models.IntegerField(blank=True, null=True)),
                ('fecha_comparendo', models.DateTimeField(blank=True, null=True)),
                ('tipo_infraccion', models.CharField(blank=True, max_length=5, null=True)),
                ('ciudad_infraccion', models.CharField(blank=True, max_length=50, null=True)),
                ('tiene_resolucion', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('tiene_cobro_coactivo', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_cobro_coactivo', models.DateTimeField(blank=True, null=True)),
                ('valor_infraccion', models.FloatField(blank=True, null=True)),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
                ('valor_notificacion', models.FloatField(blank=True, null=True)),
                ('dias_notificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_descuento_50', models.DateField(blank=True, null=True)),
                ('valor_descuento_50', models.FloatField(blank=True, null=True)),
                ('dias_descuento_50', models.IntegerField(blank=True, null=True)),
                ('fecha_descuento_25', models.DateField(blank=True, null=True)),
                ('valor_descuento_25', models.FloatField(blank=True, null=True)),
                ('dias_descuento_25', models.IntegerField(blank=True, null=True)),
                ('fecha_sin_intereses', models.DateField(blank=True, null=True)),
                ('valor_sin_intereses', models.FloatField(blank=True, null=True)),
                ('dias_sin_intereses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'multas',
                'managed': False,
            },
        ),
    ]
